/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index" |
  "/pages/component" |
  "/pages/hi" |
  "/pages/demo/index" |
  "/pages/login/index" |
  "/pages/component/ad/ad" |
  "/pages/component/audio/audio" |
  "/pages/component/button/button" |
  "/pages/component/canvas/canvas" |
  "/pages/component/checkbox/checkbox" |
  "/pages/component/cover-view/cover-view" |
  "/pages/component/editor/editor";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module "virtual:uni-pages" {
  export type LocationUrl = _LocationUrl;
}
